[spreadsheet]
spreadsheet_id = "1AbCdeFGHIJKlmnoPQRstuVWxyz1234567890abcdEFG"
worksheet_name = "Open_Ticket"

[gcp_service_account]
type = "service_account"
project_id = "noc-tools-project"
private_key_id = "197dd208aa397792b70e4b9877f6f2b8c1705084"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCptfx0ZBIEan02
UaAQcKpG+iR2ByqTsrFIQ+UA8yYOm+yx0Ptqzx6FSMJvK/44Ehc7g8fOuxTbUmYK
40Y9fkv6PHvF3DGecGA6Q+fjyAP+q0XDyo3gZzKs76g5bb/oKk5WKP+IAvsLiUPr
jj3uFpnUqVPH3yU8Ra2Do+VmP/i5dIyMDTckZhsdLJcNuG3hhoFAvV0U6WlbuWBd
7mo8BM8jlVnyGKP8ZSZSqqE0XISsah9EXliNxu2d5BeaVR5xYxwr4JXOQcgLAk6G
WHu/hyLWGk0ESWI3XeuqqTc+S8gnHIAiRPVWyCUdbYyqbVPBSvpPaWjoLLXLVPfB
BPmv7Ay3AgMBAAECggEANjX2Rx2iLbvwdFX9mdLLabHEzNj8LkLh43IgqD2DVh5T
rPdTIGq51pyH02hLpBCPUEkHnc9f2bFH/EleKg16apxAc1MjnHdMHcCMRdQiBosi
VWkSCfEdHGXPqEyZBSnibR5ahdFh7Ozzf76npLKef/J42zs6Ezc0tny3rgJYSrDc
hzV5pbGPq4TCnNPGBYVPuPQCjSbyFAQaA1Jw/qXKGkcJCQSwP2i0XZcLrwpxwPcX
gRJ6BmqEjimHsyAeCsLp8eDSMqDhY53nubfUyTsl3OnB/7v6i8L9ziyY5o7/DHOY
hd1R148I2hfNtQ2dp0F2Tgu7AFUTJXxQbNNXol1ViQKBgQDq+uthqrkbeb0VX2L3
Dyb0+QcOOT0PKVpx9WTNpflfN8e4LCbIBHK/bjzqtKJaO+yvFTRCH+Ax9nPFBARI
JNkq/g1C9KBfTnkftQpjNGrWm2+01aUljgNr2x0dhn5VxEAMpX0azX7WGkLK1IKC
f/aZODsFOTyuFVLONdVz/x8CGQKBgQC45GQCxJ3Gj3RyALm9nBFndN6dDuFwp7PE
V8Q85vbN8KTjckSIn4ppmnuy9rwLnkgtRfok5aZGvXrUJDA1h+QWxbbBtAIZwHnb
MmGZuDqUrtfHwGm+ekRKkLfDBwPAt5wcTdGPhwT7eiS5i954V60N6VE9iRCNaW1d
lLPMt9B/TwKBgByk686jFh+QToltcE33reMM/FwyhAv2GY1swZYEFosR7Km50Bxv
1mEZmhluXaAsT+Tj69PnuNe+WEx6+d6lh0ejYpB365jSoxdHZXXEbQWuOwbLSG90
iVw7gKgZvgrMepZQEhkTVdPZray2DRbFbJUu8prnaEs8VDTJATU7s1b5AoGARMlD
o/v+LuckDV3TvIUZvIGwaIImwUDDEqMMcRQEci27SpsygBnK5usAZl6BK1lhxOYp
4BxINj08OzyTavb5lrdL/Ni5h1cifrhJs2Tk9nft83TUYncefRdGJpqvfL1SqP0S
n/E9m0mf7B/rTp5f1bMd9GTP8axtcclm8xzXxuUCgYEAsKsLErEL5b8vkELdGNIX
MmGOY7QBmmX8YUscyzBig/2Pw4pXMkfLLQcdJRTFlfkbDZDg3ghWeM3imov3hIld
ZHNJbBp7lUduifoV3EPlyJ130DjOqTqKeRSLmghAiAGSmhHoxh3K8C911RnmHg9I
Bl2qKPLv4HtAhxJYHrrdPsU=
-----END PRIVATE KEY-----"""
client_email = "noc-service@noc-tools-project.iam.gserviceaccount.com"
client_id = "108972817731818636786"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/noc-service%40noc-tools-project.iam.gserviceaccount.com"